# This is for LOCAL only.
# To use production, see ./docker-compose.production.yml
version: '3'

services:
  askanybook:
    image: ghcr.io/ponelat/askanybook:latest
    env_file:
      - .env
    restart: always
    ports:
      - 80:3000
    volumes:
      - './sqlite:/app/sqlite'
      - './books:/app/books'
      
volumes:
  caddy_data: {}
  askanybook_sqlite: {}
